- name: Ensure directory exists
 ansible.builtin.file:
    path: /etc/postgresql/16/main
    state: directory
    owner: postgres
    group: postgres
    mode: 0755

- name: Create PostgreSQL Configuration File
 ansible.builtin.template:
    src: postgres_conf.j2
    dest: /etc/postgresql/16/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: 0644
