
---
- name: Add PostgreSQL APT repository key 1
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  when: inventory_hostname in groups["tag_group_psqlnodes"]

- name: Add PostgreSQL APT repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present
  when: inventory_hostname in groups["tag_group_psqlnodes"]

- name: Install PostgreSQL on Ubuntu
  apt:
    name:
      - postgresql-{{ postgres_version }}
      - postgresql-contrib
      - postgresql-client
    state: present
  become: yes
  when: inventory_hostname in groups["tag_group_psqlnodes"]


- name: Ensure PostgreSQL configuration directory exists
  file:
    path: "/etc/postgresql/{{ postgres_version }}/main"
    state: directory
    recurse: yes
  become: yes
  when: inventory_hostname in groups["tag_group_psqlnodes"]

- name: Create PostgreSQL Configuration File
  template:
    src: postgres_conf.j2
    dest: "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
  notify: Restart PostgreSQL
  when: inventory_hostname in groups["tag_group_psqlnodes"]






  
